### PR TITLE
border colors of transactions for dark mode has been change to #B6CEF…

### PR DESCRIPTION
**Pull request by Sabbirfeni**
…C80. issue solved

## Pull Request

**Related Issues:**
https://github.com/ani1609/Spendwise/issues/295

Fixes #(issue number)
#295

**Description:**
Step 1 -
ExpenseTracker.css file:
commented out  106 line.

Step 2 -
Transactions.js file:
Added "border-[#6e9df7] dark:border-[#B6CEFC80]" to className of li html tag at ine 209 and 225

**Checklist:**
- [ ✔ ] I have tested my changes.
- [ ✔ ] My code follows the project's coding standards.
- [ ] I have updated the documentation (if applicable).

**Screenshots:**
dark mode border

### CODE REVIEW

**Comment by Sabbirfeni** [comment]
I am not sure why this error is happening over here.

**Comment by ani1609** [comment]
@Sabbirfeni thats on me, dont worry

**Comment by Sabbirfeni** [comment]
Okay great

**Comment by Sabbirfeni** [comment]
This input field's border color might need to be changed on dark mode.

input field

**Comment by ani1609** [comment]
@Sabbirfeni appreciated

**Comment by Sabbirfeni** [comment]
> @Sabbirfeni appreciated

Glad to contribute on this project.

**Comment by Sabbirfeni** [comment]
> This input field's border color might need to be changed on dark mode.
> 
> input field

@ani1609 what you think about this?

**Comment by ani1609** [comment]
@Sabbirfeni actually we need to have a uniform colour coordination, all the borders should look uniformly coloured

**Comment by Sabbirfeni** [comment]
What does it mean by uniform please?

**Comment by ani1609** [comment]
@Sabbirfeni i basically mean to maintain same colour standards for elements

**Comment by Sabbirfeni** [comment]
I got it.

If you like to do so, you can assign me to the issue.

**Comment by ani1609** [comment]
@Sabbirfeni The issue has already been assigned to someone. Look for other issues to work on or feel free to raise new issues as well.

**Comment by Sabbirfeni** [comment]
Great

**Comment by Sabbirfeni** [comment]
Can we join on Linkedin?

**Comment by ani1609** [comment]
@Sabbirfeni sure

**Comment by Sabbirfeni** [comment]
This is my linkedin. Please send connect request over.
https://www.linkedin.com/in/amdadul-hoq-shabbir-185b7424a/

**Comment by ani1609** [comment]
@Sabbirfeni My portfolio website is wholly developed by me. You can see the commits in the repository.

**Pull request merged**
