### PR TITLE
Adding a Button on Login 

### LINKED ISSUE #180: FEATURE REQUEST: Develop a 'Continue with Google' button in Login.js component.
Screenshot 2023-12-11 at 8 31 04 PM

Go to client/src/components/Login.js and add a 'Continue with Google' button below the login button.

**Description:**
We're looking to enhance our user authentication experience on the frontend by adding a "Continue with Google" button. For this task, we are solely focusing on the UI implementation, and no backend logic is required at this stage.

**Tasks:**
- [ ] Create the "Continue with Google" button UI on the login/registration page.
- [ ] Ensure the button has a visually appealing and consistent design.
- [ ] Implement any necessary styling or animations for a seamless user experience.

**Additional Information:**
- The frontend is developed using React

**Notes:**
- Please only work on the UI aspects; no authentication logic build is needed at this point.
- Keep the implementation clean, modular, and well-documented.
- Test thoroughly to ensure a polished user interface.

### PR DESCRIPTION
**Pull request by SHIVAA17**
## Pull Request

**Related Issues:**
[List any related issues or reference them using the syntax `#180`.]

Fixes #180 

**Description:**
I have added continue with google button on Login page.

**Checklist:**
- [x] I have tested my changes.
- [x] My code follows the project's coding standards.
- [ ] I have updated the documentation (if applicable).

**Screenshots:**
Capture

### CODE REVIEW

**Comment by ani1609** [comment]
@SHIVAA17 can you add an animation to 'OR' just like the other elements in the form?

**Comment by SHIVAA17** [comment]
okay mentor .I will try it out.If any help is required i will ask on slack

**Comment by ani1609** [comment]
@SHIVAA17 sure

**Comment by SHIVAA17** [comment]
I have added Animation to OR (text).please review it

**Comment by SHIVAA17** [comment]
I have done.created a new branch

**Pull request merged**
