### PR TITLE
Added: Error Page

### LINKED ISSUE #335: Add: Error Page
**Describe the bug**
There is no error page (404)

**To Reproduce**
https://spendwise-seven.vercel.app/profil (speling mistake)

**Expected behavior**
Ther must be a error page and button to go back

**Screenshots**
Capture

**Additional context**
Participating in KWOC

### PR DESCRIPTION
**Pull request by AaadityaG**
## Pull Request

**Related Issues:**
Added 404 page

Fixes #335

**Description:**
[Provide a brief description of your changes.]

**Checklist:**
- [x] I have tested my changes.
- [x] My code follows the project's coding standards.
- [ ] I have updated the documentation (if applicable).

**Screenshots:**
SpendWise - Google Chrome 07-01-2024 12_49_26 PM

### CODE REVIEW

**Comment by AaadityaG** [comment]
Please add KWOC tag!

**Comment by ani1609** [comment]
@AaadityaG the 'KWoC' tag has already been added in the issue you are working on. Dont worry

**Comment by ani1609** [comment]
@AaadityaG your PR is facing problem while deployment

Screenshot 2024-01-07 at 1 28 43 PM

**Comment by ani1609** [comment]
@AaadityaG seems like the deployment related issue from my end. Please wait while I check the reason behind the issue.

**Comment by ani1609** [comment]
@AaadityaG seems like your code has not followed the ESLint rules and hence the PR is not deploying successfully. Please commit your changes after solving the ESLint errors properly.

**Comment by AaadityaG** [comment]
@ani1609 bro any idea/suggetion how can I fix this?

**Comment by ani1609** [comment]
@AaadityaG pretty easy, you just need to follow up the ESLint rules and those are very straight forward

**Comment by ani1609** [comment]
@AaadityaG Feel free to reach out to me on our Slack channel if you need assistance or guidance to resolve the issue. I'm more than happy to help you out!

**Comment by AaadityaG** [comment]
raise new pr

**Pull request closed without merging**
