### PR TITLE
Implementing Validation and Error Handling in Signup Form

### PR DESCRIPTION
**Pull request by ayann07**
## Pull Request

**Related Issues:**
[List any related issues or reference them using the syntax `#issue_number`.]
Fixes #(issue number)
issue number : #229 
**Description:**
[Provide a brief description of your changes.]
I have implemented validation of password and name fields.
**Checklist:**
- [yes ] I have tested my changes.
- [ yes] My code follows the project's coding standards.
- [ ] I have updated the documentation (if applicable).

**Screenshots:**
[If applicable, include screenshots to help reviewers understand your changes.]
verification

I have worked on this under KWOC 2023.

### CODE REVIEW

**Comment by ani1609** [comment]
@ayann07 seems like there is an error. the error message is show before even filling up the form


https://github.com/ani1609/Spendwise/assets/89239354/896dd962-4dce-4c17-899b-8deee4cbaaf3

**Comment by ayann07** [comment]
It is not an error message,I just displayed it earlier only so that user knows the conditions while setting the password.

**Comment by ayann07** [comment]
If you want I can render it afterwards, but I had seen on many sign up forms that the instructions for setting up password are already mentioned for user.

**Comment by ani1609** [comment]
@ayann07 well, your view is quite logical and yeah we should have a early message to the users. But can you like change the ui, currently this looks like the user is prompted with an error even before filling the form. And also use a delayed animation fr rendering it

**Comment by ayann07** [comment]
I have now made the necessary changes, please check adn let me know if there require anymore improvement.
Screenshot (882)

**Comment by ani1609** [comment]
@ayann07 this type of design is causing overflowing issues for screens with lower heights and thats is quite expected if we keep the hint that long. In order to deal with this problem, lets just prompt the hint in password input placeholder and keep the error message same as that of non matched passwords and existing users error.

Consider the following follow ups
Screenshot 2024-01-01 at 1 14 20 PM
Screenshot 2024-01-01 at 1 14 29 PM

**Comment by ayann07** [comment]
Now I have done the changes, please check.

**Comment by ani1609** [comment]
@ayann07 your changes have a bug. I just entered an invalid password, it should be the error, but still i got my account created.

**Comment by ani1609** [comment]
@ayann07 and please try to keep the red coloured error in a single line and as mentioned earlier in the images. Also keep the validation check only for 8 characters and not any uppercase or lowercase or special characters

**Comment by ayann07** [comment]
Should I remove the upper case lower case validation?

**Comment by ayann07** [comment]
The issue raised said that the password should incorporate the upper,lower special and numeric characters

**Comment by ani1609** [comment]
@ayann07 yeah i am very well aware of that but as we saw, fitting such a long prompt is a bit inconvenient. So keep the checking for >=8 characters as of now

**Comment by ayann07** [comment]
Now you may check, I have removed the bug and implemented the only check for length to the password field.

**Comment by ani1609** [comment]
@ayann07 appreciated

**Pull request merged**
