### PR TITLE
Eslint setup for both client and server

### LINKED ISSUE #244: Add ESLint for better code readability and uphelding set coding rules
**Is your feature request related to a problem? Please describe.**
The current project lacks consistent formatting standards or code formatters and linters, leading to potential readability issues and difficulties in maintaining the codebase.

**Describe the solution you'd like**
Implement ESLint for the project to enforce consistent coding standards, identify potential errors, and maintain code quality across the codebase. ESLint will help ensure adherence to predefined coding conventions, enhancing code readability and reducing the likelihood of bugs or inconsistencies.

**Describe alternatives you've considered**
Prettier can be implemented which is just a code formatter, so it would only check discrepancies in code through pre-set rules.However, ESLint is widely adopted and provides robust customization options and extensibility, making it a versatile and popular choice for code analysis and enforcement.

### PR DESCRIPTION
**Pull request by mendacium-a11y**
## Pull Request

**Related Issues:**

Fixes #244 

**Description:**
set up eslint for client and server, along with scripts in package.json

**Checklist:**
- [x] I have tested my changes.
- [x] My code follows the project's coding standards.
- [x] I have updated the documentation (if applicable).

### CODE REVIEW

**Review by niladrix719 — CHANGES_REQUESTED** [review]
Can we also apply it on `client/tailwind.config.js`?

**Comment by mendacium-a11y** [comment]
> Can we also apply it on `client/tailwind.config.js
you can check now, i have updated the scripts

**Review by niladrix719 — APPROVED** [review]
Looks Perfect!

**Comment by mendacium-a11y** [comment]
happy to hep :smile:

**Pull request merged**
