### PR TITLE
Made a toggle to show password on login page

### PR DESCRIPTION
**Pull request by mendacium-a11y**
## Pull Request

**Related Issues:**
#246 

Fixes #(issue number)

**Description:**
added a button in the password input field to toggle hiding password or not

**Checklist:**
- [x] I have tested my changes.
- [x] My code follows the project's coding standards.
- [ ] I have updated the documentation (if applicable).

**Screenshots:**

Screenshot from 2023-12-30 20-10-54
Screenshot from 2023-12-30 20-10-59

### CODE REVIEW

**Review by ani1609 — CHANGES_REQUESTED** [review]
Please make the cursor as pointer and decrease the size of the icon by a little.

**Comment by mendacium-a11y** [comment]
> Please make the cursor as pointer and decrease the size of the icon by a little.

what do you mean by cursor as pointer?

**Comment by ani1609** [comment]
the style of the cursor should change to pointer when the user hovers over the eye icon

**Comment by mendacium-a11y** [comment]
all done

**Review by ani1609 — APPROVED** [review]

**Pull request merged**
