### PR TITLE
Fixed form border color in dark mode

### LINKED ISSUE #294: Change transaction form input border colours
Screenshot 2023-12-29 at 2 17 03 PM

Change the border colours of 'Amount'. 'Category', 'Description', and 'Date' forms to '#B6CEFC80' when in dark mode

### PR DESCRIPTION
**Pull request by ShahnawazHussain28**
## Pull Request

Fixes #294 

**Description:**
As 'important' properties can't be changed in the tailwind classes. They needed to be overwritten in the css file only. Modified the ExpenseTracker.css file to add support of the dark mode without removing the !important tag as you specified.

### CODE REVIEW

**Comment by ani1609** [comment]
Current ui-
Screenshot 2023-12-30 at 1 01 46 AM

Your PR preview-
Screenshot 2023-12-30 at 12 33 57 PM
you have mistakenly changed the button colour and icon's colour and background-colours

**Comment by ShahnawazHussain28** [comment]
The current UI already looks like this. It is the main branch of your repo

image

**Comment by ani1609** [comment]
@ShahnawazHussain28 actually it is not. please have a look into the live link

**Comment by ani1609** [comment]
@ShahnawazHussain28 appreciated

**Pull request merged**
