### PR TITLE
Made a toggle to show password on login page

### PR DESCRIPTION
**Pull request by mendacium-a11y**
## Pull Request

**Related Issues:**
#246 

Fixes #(issue number)

**Description:**
added a button in the password input field to toggle hiding password or not

**Checklist:**
- [x] I have tested my changes.
- [x] My code follows the project's coding standards.
- [ ] I have updated the documentation (if applicable).

**Screenshots:**
Screenshot from 2023-12-23 17-55-15
Screenshot from 2023-12-23 17-55-20

### CODE REVIEW

**Comment by ani1609** [comment]
@mendacium-a11y you have messed up the animation. please fix it and keep it as like before.

**Comment by mendacium-a11y** [comment]
ok let me check

**Comment by mendacium-a11y** [comment]
so the problem seems to be that vanilla css and tailwind are being used together and hence, not being able to achieve the desired result

**Comment by mendacium-a11y** [comment]
am trying to figure out how to make it work, might have to convert all to tailwind

**Comment by ani1609** [comment]
@mendacium-a11y the css properties may be over ridding each others. Use insect from browser.

**Comment by mendacium-a11y** [comment]
I am really sorry for going awol on this issue, had some things come up, just hadn't had the chance to jump back on it

**Comment by ani1609** [comment]
@mendacium-a11y okay no worries, please complete the issue.

**Comment by mendacium-a11y** [comment]
yeah definitely, thanks for understanding

**Pull request closed without merging**
