### PR TITLE
filter forms styled

### LINKED ISSUE #151: FEATURE REQUEST: Add styles to the filter forms
Screenshot 2023-12-10 at 4 59 17 PM

Refer to the ExpenseTracker.js file and add styles to the filter section according to the above Ui.

### PR DESCRIPTION
**Pull request by GautamRaj-12**
## Pull Request

Fixes #151 

**Description:**
Added styles to filter forms. Borders added ,layout corrected.

**Checklist:**
- [x] I have tested my changes.
- [x] My code follows the project's coding standards.
- [ ] I have updated the documentation (if applicable). 

**Screenshots:**

https://github.com/ani1609/Spendwise/assets/64408989/bb470994-f14c-4b1d-b1ea-cade59961762

### CODE REVIEW

**Comment by GautamRaj-12** [comment]
On width less than 360 px, it starts to shrink too much. What should I do? Should I wrap them or any other idea?

**Comment by ani1609** [comment]
@GautamRaj-12 We only need to make the designs responsive till the width of 360px. Thats the lowest limit of consideration, screens widths below that are not considered.

**Comment by ani1609** [comment]
@GautamRaj-12 Good job Gautam.

**Comment by GautamRaj-12** [comment]
Thanks

**Pull request merged**
