### PR TITLE
feat:filter by category feature added

### LINKED ISSUE #123: FEATURE REQUEST: DEVELOP A CATEGORY BASED FILTER FEATURE
**Is your feature request related to a problem? Please describe.**
The users cannot filter out the expense transactions for a given category. For example if someone wants to know what are the transactions he/she has made in 'Food' category, he /she has to manually search for the transactions made for food.

**Describe the solution you'd like**
The users should be able to filter out their expense transactions based on category (just like the filter feature available for transaction type wise filter and date wise filter).

Make sure you join our slack channel for better discussions and other announcements.

### PR DESCRIPTION
**Pull request by GautamRaj-12**
Fixes #123 

Here is the working demo of the feature I implemented:

https://github.com/ani1609/Spendwise/assets/64408989/377bc457-a662-436a-8dce-5b5455fb7464

Here is how I did it:

1. Created a new state for selected category
image

2. The following line is used to update the state variable selectedCategory with the category of the transaction being edited.
image

3. The following line is added to the Firestore query used in the handleDelete function. This addition ensures that when a user deletes a transaction, the deletion is specific to both the transaction ID and the selected category.
image

4. A handleCategory function created to filter data based on category.
image

5. Dropdown created for users to select categories
image

### CODE REVIEW

**Review by ani1609 — CHANGES_REQUESTED** [review]
There seems to be an error. Suppose i have filtered out the transactions based on particular category and then after i add a transaction, transactions of all categories show up (inspite of there being a filter applied before hand).

https://github.com/ani1609/Spendwise/assets/89239354/441a0b9f-f69a-49df-af7b-6ce0aa6a4f10

**Comment by GautamRaj-12** [comment]
Ok. 
Have a look now.
Created a function to fetch and update transactions and called the function when submit is clicked. Also the same issue was there when we delete any particular thing. So called the function from there too.

https://github.com/ani1609/Spendwise/assets/64408989/914bc69c-ddbc-4706-b1ef-ba0a395c879a

**Review by ani1609 — CHANGES_REQUESTED** [review]
There seems to be an abruptness in the behaviour of the transactions when a new transaction is added with a category based filter applied previously. The bug can be seen in your screen recording itself.

**Comment by GautamRaj-12** [comment]
That flicker thing on the User Interface?

**Comment by GautamRaj-12** [comment]
Ok. I am working on it

**Comment by ani1609** [comment]
Yes please fix that. You can refer to the code behind date and transaction type based filters, it had some similar issues in the beginning.

**Comment by GautamRaj-12** [comment]
So previously I think , I created extra functions that weren't necessary and that was causing that flickering issue. Upon your advise to look at existing code, I found that existing code had enough to handle this. Only slight modifications were necessary. 

So basically just created a state for categoryFilter and in the existing useEffect where transactionType and dateFilter were there, added categoryFilter logic there

So reverted back all my previous commits for getting original code and made fresh changes.
Here is the recording of the working:

https://github.com/ani1609/Spendwise/assets/64408989/579e1e28-6f90-4495-84cc-790d7244171e

**Review by ani1609 — CHANGES_REQUESTED** [review]
The category based filter seems to be working fine, but there is still minor issue. Say for example a user sorts out the transactions based on 'Food', after seeing that the user must be allowed to clear the filter. You can do this by giving an option as 'All' in the select form. You can refer the transaction type filter for this.

**Comment by GautamRaj-12** [comment]
Have a look now, I have added the All option

https://github.com/ani1609/Spendwise/assets/64408989/18da1738-5049-4086-b6c7-edb6e048dfb9

**Review by ani1609 — APPROVED** [review]

**Comment by ani1609** [comment]
@GautamRaj-12 perfect. The 'never give up' attitude of yours is appreciated. Keep learning.

**Comment by GautamRaj-12** [comment]
Thank you. Learned a lot.  One query: Will This contribution be counted in the KWOC stats?

**Comment by niladrix719** [comment]
@GautamRaj-12 Sure it will, but i think They haven't updated it. But no worries once they will update it , this PR will be counted in KWoC

**Comment by GautamRaj-12** [comment]
Ok. Thanks.

**Pull request merged**
