### PR TITLE
animation added for sign up login process

### LINKED ISSUE #173: FEATURE REQUEST: Add a loading screen after the user clicks on the login and signup buttons.
After the user clicks the login or signup button after filling the required credentials, it is not know to the user that he/she has clicked the button for sure or not.

To overcome this issue, develop a loading screen or animation which can be showed as soon as the user clicks on the login or signup button.

### PR DESCRIPTION
**Pull request by GautamRaj-12**
## Pull Request

Fixes #173 

Implemented a loading state to indicate whether a login/signup process is ongoing. Utilized conditional rendering to display a spinner until the process completes after a user click. The spinner is styled with the primary color to seamlessly integrate with the website's accent, ensuring a cohesive visual experience.

- [x] I have tested my changes.
- [X] My code follows the project's coding standards.
- [x] I have updated the documentation (if applicable).

On clicking Sign Up

https://github.com/ani1609/Spendwise/assets/64408989/7b319b7b-61b5-4b89-ac72-bee7d5369a89

On clicking Log in

https://github.com/ani1609/Spendwise/assets/64408989/f9b02d25-73da-4b14-91eb-c986b423f259

Here is a recording with a 1s delay to properly view the animation

https://github.com/ani1609/Spendwise/assets/64408989/9f64ba85-fb2f-41e1-9523-46925b16f434

### CODE REVIEW

**Comment by ani1609** [comment]
@GautamRaj-12 why is the signup form coming up once again after clicking the submit button?

**Comment by ani1609** [comment]
@GautamRaj-12 you also need to handle the edge cases (invalid email or password, passwords do not match and user already exists)

**Comment by GautamRaj-12** [comment]
Ok.. tell me. That will be helpful..

**Comment by GautamRaj-12** [comment]
ok @ani1609

**Comment by GautamRaj-12** [comment]
Login - Invalid Username or Password

https://github.com/ani1609/Spendwise/assets/64408989/9ea04601-fdb5-42a6-868f-0a2437374c60

Login - Successful Login

https://github.com/ani1609/Spendwise/assets/64408989/7d4a006f-8aa8-4443-aad3-c7d2f1713aac

Signup - User Already exists

https://github.com/ani1609/Spendwise/assets/64408989/3c818bfe-0579-4256-b61c-2e049deb2491

Signup - New User Registered

https://github.com/ani1609/Spendwise/assets/64408989/9039ba1c-ea63-49df-9802-635ad63099f4

Signup - Passwords do not match - Animation happens too fast to be seen properly

https://github.com/ani1609/Spendwise/assets/64408989/4be2750a-60f5-43c5-9cc7-f4d2a85d07ba

Signup - Passwords do not match - Some delay using setTimeOut to see the spinner (Not implemented in actual code, just for visualising)

https://github.com/ani1609/Spendwise/assets/64408989/c3a845e5-4ac1-4695-8dda-3b0d23d8473e

**Pull request closed without merging**
