### PR TITLE
FIX: long description breaks the UI

### LINKED ISSUE #149: Bug: Very Long Description Breaks the UI
**Describe the bug**
Very Long Description of transaction Breaks the ui

**To Reproduce**
1. Go to https://spendwise-seven.vercel.app
2. Add a Transaction with a very long description
3. See error

**Expected behavior**
We can show starting words and hide the rest to have a better UI

**Screenshots**
Screenshot 2023-12-10 at 4 35 16 PM

### PR DESCRIPTION
**Pull request by Jaimin25**
## Pull Request

**Related Issues:**
[List any related issues or reference them using the syntax `#issue_number`.]

Fixes #149 

**Description:**
Changed the length of chars to be shown on different screens and also tested on different screen size.

**Checklist:**
- [x] I have tested my changes.
- [x] My code follows the project's coding standards.
- [ ] I have updated the documentation (if applicable).

**Screenshots:**

https://github.com/ani1609/Spendwise/assets/65119631/d6d65f6e-70a1-4334-9274-6986ce50823c

### CODE REVIEW

**Comment by Jaimin25** [comment]
should work fine now ig

**Review by ani1609 — CHANGES_REQUESTED** [review]
@Jaimin25 the issue still persists 

Screenshot 2023-12-10 at 8 16 00 PM


this is at 408px

**Comment by Jaimin25** [comment]
> @Jaimin25 the issue still persists
> 
> Screenshot 2023-12-10 at 8 16 00 PM
> this is at 408px

image
its cause the screen size is checked when the component is loaded not every time the screen changes.
will change it to screen change

**Comment by Jaimin25** [comment]
This will change the character length on screen resize and the text description length with get updated.
image

https://github.com/ani1609/Spendwise/assets/65119631/f9a988bc-b5d5-4e7b-917c-876b8fb8f4d6

**Review by ani1609 — APPROVED** [review]

**Comment by ani1609** [comment]
@Jaimin25 perfect one finally.

**Pull request merged**
