### PR TITLE
FILTER UI TWEAK: Change the Ui of the Transaction type drop down menu of filter.

### PR DESCRIPTION
**Pull request by anand-harsh**
## Pull Request

**Related Issues:**
Issue: #174 

Fixes #(issue number)

**Description:**
Updated  Ui of the Transaction type drop down menu of filter.

**Checklist:**
- [x] I have tested my changes.
- [x] My code follows the project's coding standards.
- [x] I have updated the documentation (if applicable).

**Screenshots:**

image

image

This image is while you hover on options

### CODE REVIEW

**Comment by ani1609** [comment]
@anand-harsh please follow up the sample carefully. The required designs are different from what you have developed

It should be like this
https://github.com/ani1609/Spendwise/assets/89239354/7bdc0aae-065c-4857-9865-8644e7c5787e

**Comment by anand-harsh** [comment]
> @anand-harsh please follow up the sample carefully. The required designs are different from what you have developed
> 
> It should be like this
> 
>  Screen.Recording.2023-12-13.at.5.11.29.PM.mov

I have tried fixing it, see if it is okay

image

**Comment by ani1609** [comment]
@anand-harsh please refer to the video in comment https://github.com/ani1609/Spendwise/pull/203#issuecomment-1853768304 carefully. You are not matching the ui according to the ui shown in the video.

**Comment by anand-harsh** [comment]
> @anand-harsh please refer to the video in comment [#203 (comment)](https://github.com/ani1609/Spendwise/pull/203#issuecomment-1853768304) carefully. You are not matching the ui according to the ui shown in the video.

image

How about this one?

**Pull request closed without merging**
