### PR TITLE
dark mode toggle feature

### LINKED ISSUE #121: Feature Request: Implement a Dark Mode for the SpendWise UI with a toggle option
Is your feature request related to a problem? Please describe.
Using SpendWise in low-light conditions is straining on the eyes without a Dark Mode, impacting overall user experience.

Describe the solution you'd like
Implement a Dark Mode in the SpendWise UI, providing users with the option to toggle between light and dark interfaces for improved usability, especially in low-light environments.

Make sure you join our slack channel for better discussions and other announcements.

### PR DESCRIPTION
**Pull request by ghost**
## Pull Request

**Related Issues:**
[This PR adds Dark mode Toggle feature ]

Fixes #121 

**Screenshots:**
Screenshot from 2023-12-09 20-01-00

### CODE REVIEW

**Review by niladrix719 — COMMENTED** [review]
The white border lines seems too white for a dark background can we reduce it to less white and more light grey type

**Comment by Aloksh42** [comment]
Hey @niladrix719 I could this much is it ok ?    
Screenshot from 2023-12-10 20-00-03

**Comment by ani1609** [comment]
@Aloksh42 Please put this issue to hold. we have an ui/ux designer with us and as soon as the dark ui is confirmed (probably by tomorrow), i will share it and you can do the required stylings for that.

**Comment by ani1609** [comment]
Hey @Aloksh42, are you working on this?

**Comment by Aloksh42** [comment]
Sorry I may take some time to work on this, you can unassign me and assign others if you want?

**Pull request closed without merging**
