### PR TITLE
Passwordicontoggle

### PR DESCRIPTION
**Pull request by SHIVAA17**
## Pull Request

**Related Issues:**
[List any related issues or reference them using the syntax `#318`.]

Fixes #(318)

**Description:**
Added a password icon show/hide for password and confirm password
**Checklist:**
- [ ] I have tested my changes.
- [ ] My code follows the project's coding standards.
- [ ] I have updated the documentation (if applicable).

**Screenshots:**
[If applicable, include screenshots to help reviewers understand your changes.]
image

### CODE REVIEW

**Comment by ani1609** [comment]
@SHIVAA17 you have messed up the animations. Please refer to the previous designs and keep the same animations

**Comment by SHIVAA17** [comment]
made the changes

**Comment by ani1609** [comment]
@SHIVAA17 i have solved the merge conflicts but seems like your code has not followed the ESLint rules and hence the PR is not deploying successfully. Please commit your changes after solving the ESLint errors properly.

**Comment by ani1609** [comment]
@SHIVAA17 Feel free to reach out to me on our Slack channel if you need assistance or guidance to resolve the issue. I'm more than happy to help you out!

**Comment by SHIVAA17** [comment]
okay

**Pull request closed without merging**
